/* was user but is special name ? */
CREATE TABLE Account(
    USERID INTEGER NOT NULL  PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);
 

CREATE TABLE post(
    POSTID INTEGER NOT NULL  PRIMARY KEY,
    TITLE VARCHAR(100),
    CONTENT VARCHAR(500),
    USERID INTEGER NOT NULL,
    FOREIGN KEY (USERID) REFERENCES Account(USERID)
);

    